### ISSUE TITLE
オーラス・リーチ宣言牌に対してロンした牌譜について和了者が1000点余分に加点されている

### ISSUE THREAD

**Issue by riko-mushigatake** [kbkn3/MahjongSoul-review-supporter#12]
再現方法：https://game.mahjongsoul.com/?paipu=240227-c46da737-2669-4b8c-9de0-8379f2e8df9d_a468486926
の牌譜を表示して解析を実施する。

結果：
上記東風戦のオーラスの点数移動について下記の通り齟齬がある:
- 2000点を和了した者が+3000点
- リーチ宣言牌をロンされた放銃者が-2000点

期待値：
和了・放銃者の点数移動が±2000点

オーラスの和了なので、NAGA解析の本質的な利用には問題ありませんが一応報告しておきます。

**Comment by kbkn3** [comment]
@riko-mushigatake 
ご報告ありがとうございます！

大変遅くなりました。
v1.3.0で対応させて頂きました。
