### ISSUE TITLE
雀魂の牌譜をMortalで開くと、Game URLが空の状態のサイトに遷移する

### ISSUE THREAD

**Issue by hiro-mi** [kbkn3/MahjongSoul-review-supporter#14]
再現方法
- 任意の雀魂の牌譜を開く
（例：https://game.mahjongsoul.com/?paipu=240227-c46da737-2669-4b8c-9de0-8379f2e8df9d_a468486926 ）
- いずれかのユーザーを選択してMortalでの解析を試みる

結果：
- 遷移先サイト（https://mjai.ekyu.moe/)の「Game URL (Tenhou, Mahjong Soul)」の部分に牌譜URLが入力されない

期待値：
- 遷移先サイトの「Game URL (Tenhou, Mahjong Soul)」の部分に牌譜URLが入力される

環境：
- 雀魂（日本版）
- Windows 11
- Chorme  122.0.6261.131（Official Build） （64 ビット）
- 雀魂牌譜検討サポーター 1.2.0

以前動作していることを確認しておりましたが、最近はURLが途中で切れる現象が起きており、そちらを報告しようとしておりました。
本日上記現象の再現を試みたところ、そもそもURLが入力されていない状況となっていましたので、このような報告となりました。
他になにか必要な情報ありましたら追記します。よろしくお願いします。

**Comment by kbkn3** [comment]
@hiro-mi
報告ありがとうございます！ 
v1.2.1で解決できているでしょうか？
私の環境では入力はできるようになりました。
（上記の牌譜だと東風なので解析は弾かれました）

**Comment by hiro-mi** [comment]
@kbkn3 修正確認しました、ありがとうございました！
