### ISSUE TITLE
Edge版のアドオンのバージョンが v1.1.3 のままになっている

### ISSUE THREAD

**Issue by riko-mushigatake** [kbkn3/MahjongSoul-review-supporter#16]
挙動：
下記のEdge版のアドオンのバージョンがv.1.1.3のままになっている
https://microsoftedge.microsoft.com/addons/detail/%E9%9B%80%E9%AD%82%E7%89%8C%E8%AD%9C%E6%A4%9C%E8%A8%8E%E3%82%B5%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%BC/jopdfhmfehndjpnjjidmkkmjmkaebodb

期待値：Chrome版と同じくv1.2.1

コメント：
Edge版をずっと使っていてptEV機能が実装されているはずなのに出てこないなーと思ってました。
できればEdge版もアップデートいただけると助かります。

**Comment by kbkn3** [comment]
申し訳ありません！！
見落としていました！
明日の夜storeに提出致します。

**Comment by kbkn3** [comment]
@riko-mushigatake 
v1.2.1がリリースされました。
大変お待たせ致しました。
https://microsoftedge.microsoft.com/addons/detail/%E9%9B%80%E9%AD%82%E7%89%8C%E8%AD%9C%E6%A4%9C%E8%A8%8E%E3%82%B5%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%BC/jopdfhmfehndjpnjjidmkkmjmkaebodb

**Comment by riko-mushigatake** [comment]
@kbkn3 : 起動して1.2.1 になっていることを確認しました。ニコニコが落ちているためそれ以上の動作確認はできませんでしたが、ご対応ありがとうございました。
重箱の隅をつつく話ですが、ストアの詳細情報にあるアップデート情報が古いままなので適宜修正されると良いかもしれません。

**Comment by kbkn3** [comment]
@riko-mushigatake 
ありがとうございます！
申請とセットで修正となるので、次回アップデート時にまとめて申請したいと思います。
