### ISSUE TITLE
Cannot get, Try Reload first

### ISSUE THREAD

**Issue by Omote23** [kbkn3/MahjongSoul-review-supporter#3]
Uhh.. I followed the instruction. but it doesn't work popping that error message
Doesn't NA server support this extension program?

**Comment by kbkn3** [comment]
Sorry ....
The logic to insert the script had the wrong settings for EN/NA Server and CHINA Server.
Please wait a bit while we fix it and release it.

**Comment by kbkn3** [comment]
#4 The fix is complete and will be released as soon as the Chrome Web Store finishes reviewing it.
We will close this issue when the relevant version is released.

**Comment by kbkn3** [comment]
I believe it is available now that it has been safely released from the various stores. What do you think?

**Comment by iceshoesss** [comment]
> @Omote23 I believe it is available now that it has been safely released from the various stores. Are you able to use it?

sorry, it still can't work.
version: 1.1.3
