### ISSUE TITLE
名前に半角"&"が含まれているとNAGAが”1番目のurlに誤りがあります”とエラーを出す

### ISSUE THREAD

**Issue by riko-mushigatake** [kbkn3/MahjongSoul-review-supporter#9]
再現方法：
https://game.mahjongsoul.com/?paipu=230129-0b0d070d-3986-4872-a8cd-3c67a9b89625_a468486926
の牌譜を表示して解析を実施する。

結果：NAGAが”1番目のurlに誤りがあります”とエラーを出す。

回避手段：
json内にある半角"&"を全角"＆"などに置き換えれば問題なく解析できる。

試していませんが、URLエンコードが必要な文字が入っていると同様の問題が起きるかもしれません。
いつも便利に使わせていただいています。ありがとうございます。

**Comment by kbkn3** [comment]
ありがとうございます！
除去対象の記号に加えます。

アップデートをお待ち下さい！

**Comment by kbkn3** [comment]
@riko-mushigatake 
本日chrome/edgeともにv1.1.3をリリースし、報告頂いた問題に対応しました。
現時点で雀魂のプレイヤーネームで利用が確認されているURLで利用できない半角記号を全角記号に変換する処理を加えています。

報告ありがとうございました！

https://naga.dmv.nico/htmls/eba00cb11da33125afb905093c376d58ef685a0f6d16a2811cfa6c6a367e0525v2_2_2.html?tw=0
